name: Build Release (AUR)

on:
  release:
    types: [published]
    
permissions:
  contents: write
  
jobs:
  aur-update-git:
    runs-on: ubuntu-latest 
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Prepare structure
        run: mkdir -p ./aur/pocketnet

      - name: AUR Update
        uses: TheWisker/aur-update@master
        with:
          aur_key: ${{ secrets.AUR_KEY }}
          repo_name: pocketnet
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
