name: Build Release (AUR)

on:
  workflow_dispatch:
  release:
    types: [published]
    
permissions:
  contents: write
  
jobs:
  aur-update-git:
    runs-on: ubuntu-latest 
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Prepare structure
        run: mkdir -p ./aur/pocketnet
      - name: AUR Update
        uses: TheWisker/aur-update@master
        with:
          aur_key: ${{ secrets.AUR_KEY }}
          repo_name: pocketnet
          tag_name: 0.9.114
